# General Settings
title: "Vishvena - Let's Build"
email: "info@vishvena.com"
email_2: "support@vishvena.com"
description: >- # this means to ignore newlines until "baseurl:"
  At VISHVENA TECHNO SOLUTIONS, our mission is centered on innovation, with a distinct focus on patent-driven expertise.
  Specializing in the dynamic realms of Artificial Intelligence, groundbreaking innovations, and the development of
  cutting-edge hardware and software, we are committed to pushing the boundaries of what’s possible in the tech landscape.
favicon: "/assets/images/favicon.webp"

# Seo Meta Settings
meta_og_image: "/assets/images/meta-image.webp"
meta_twitter_image: "/assets/images/meta-image.webp"

# Site Wide Theme Color Setting
color_scheme: Blue # Aqua Blue Brown Cobalt Green Hibiscus Leaf Meander Orange Pink Purple Red Rose Sky Teal Violet Yellow

# Site Wide Theme Font Setting
font_scheme:  # Jost, Nunito , DM Sans + Zilla Slab , HK Grotesk, Abhaya, Libre


# Sitewide Logo
black_logo_1x: "/assets/images/vishvena-logo.png"
black_logo_2x: "/assets/images/vishvena-logo.png"
light_logo_1x: "/assets/images/vishvena-logo.png"
light_logo_2x: "/assets/images/vishvena-logo.png"

address_01: 'No. 4-28/36/1, Kandi, Saraswati Temple Kandi,<br>Sangareddy Medak 502285 Telangana'
phone_number: "+91 9663089241"
copyright_text: "© 2024 Vishvena. All rights reserved."

google_analytics:
  enable: true
  key: "G-FZTS82VKC2"  # UA-664136761-1

google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

social_accounts:
  title: "Follow Us"
  links:
    - url: "#"
      icon: "jam jam-twitter"

    - url: "#"
      icon: "jam jam-facebook"

    - url: "#"
      icon: "jam jam-instagram"

    - url: "#"
      icon: "jam jam-youtube"


external_links:
  title: "Learn More"
  links:
    - url: "#"
      text: "About Us"
    - url: "#"
      text: "Our Story"
    - url: "#"
      text: "Projects"
    - url: "#"
      text: "Pricing"
    - url: "#"
      text: "Features"


external_links_02:
  title: "Need Help?"
  links:
    - url: "#"
      text: "Support"
    - url: "#"
      text: "Get Started"
    - url: "#"
      text: "Contact Us"
    - url: "#"
      text: "Terms of Use"
    - url: "#"
      text: "Privacy Policy"


external_links_03:
  title: "Company"
  links:
    - url: "#"
      text: "Our Team"
    - url: "#"
      text: "Strategy"
    - url: "#"
      text: "Service"
    - url: "#"
      text: "Mission"
    - url: "#"
      text: "Process"

footer_newsletter:
  title: "Our Newsletter"
  sub_title: "Subscribe to our newsletter to get our news & deals delivered to your inbox!"
  subscribe_button_text: "Join"


one_page_nav_settings:
  links:
    - text: "Home"
      url: "#home"
    - text: "Services"
      url: "#services"
    - text: "Experiences"
      url: "#experiences"
    - text: "Portfolio"
      url: "#portfolio"
    - text: "Testimonials"
      url: "#testimonials"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/art/bg31.webp"

gallery:
  images:
  - img: "/assets/images/art/z1.svg"
  - img: "/assets/images/art/z2.svg"
  - img: "/assets/images/art/z3.svg"
  - img: "/assets/images/art/z4.svg"
  - img: "/assets/images/art/z5.svg"
  - img: "/assets/images/art/z6.svg"
  - img: "/assets/images/art/z7.svg"
  - img: "/assets/images/art/z8.svg"
